/**
 * District store — backed by Neon Postgres.
 * Same interface as the old JSON-file version so API routes don't need changes.
 */
import { getSql } from "@/lib/db";
import { slugify } from "@/lib/slugify";

export interface DistrictRecord {
  id: string;
  labelAz: string;
  labelRu: string;
  pricePerSqm: number;
  updatedAt: string; // ISO 8601
}

type Row = { id: string; label_az: string; label_ru: string; price_per_sqm: number; updated_at: Date | string };

function toRecord(row: Row): DistrictRecord {
  return {
    id: row.id,
    labelAz: row.label_az,
    labelRu: row.label_ru,
    pricePerSqm: Number(row.price_per_sqm),
    updatedAt: new Date(row.updated_at).toISOString(),
  };
}

export async function getDistricts(): Promise<DistrictRecord[]> {
  const sql = getSql();
  const rows = await sql`SELECT * FROM districts ORDER BY label_az` as Row[];
  return rows.map(toRecord);
}

/** @deprecated Use getDistricts(). Kept for backward compat with existing API routes. */
export const readStore = getDistricts;

export async function createDistrict(data: {
  labelAz: string;
  labelRu: string;
  pricePerSqm: number;
}): Promise<DistrictRecord> {
  const sql = getSql();
  const id = slugify(data.labelAz);
  const rows = await sql`
    INSERT INTO districts (id, label_az, label_ru, price_per_sqm)
    VALUES (${id}, ${data.labelAz}, ${data.labelRu}, ${data.pricePerSqm})
    RETURNING *
  ` as Row[];
  return toRecord(rows[0]);
}

export async function updateDistrict(
  id: string,
  data: { labelAz: string; labelRu: string; pricePerSqm: number }
): Promise<DistrictRecord | null> {
  const sql = getSql();
  const rows = await sql`
    UPDATE districts
    SET label_az = ${data.labelAz},
        label_ru = ${data.labelRu},
        price_per_sqm = ${data.pricePerSqm},
        updated_at = NOW()
    WHERE id = ${id}
    RETURNING *
  ` as Row[];
  return rows[0] ? toRecord(rows[0]) : null;
}

export async function deleteDistrict(id: string): Promise<boolean> {
  const sql = getSql();
  const rows = await sql`DELETE FROM districts WHERE id = ${id} RETURNING id` as { id: string }[];
  return rows.length > 0;
}

/** Kept for backward compat — district IDs are now generated by createDistrict. */
export function generateId(labelAz: string): string {
  return slugify(labelAz);
}
